# Generated by Django 3.1.7 on 2021-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qz', '0003_remove_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choiceA',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceA_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceB',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceB_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceC',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceC_is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceD',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choiceD_is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
