# Generated by Django 3.1.7 on 2021-06-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qz', '0004_auto_20210603_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
