# Generated by Django 3.1.7 on 2021-06-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qz', '0005_delete_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question1', to='qz.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question2', to='qz.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question3', to='qz.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question4', to='qz.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question5', to='qz.question'),
        ),
    ]
