# Generated by Django 3.1.7 on 2021-06-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qz', '0006_auto_20210603_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='Quiz_title',
            new_name='quiz_title',
        ),
    ]
