# Generated by Django 3.2 on 2021-06-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qz', '0009_auto_20210616_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question3', to='qz.question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question4', to='qz.question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question5', to='qz.question'),
        ),
    ]
